### Создание пользователя
POST http://localhost:8080/users/add
content-type:application/json

{
  "firstName": "Dmitiry",
  "lastName": "Dmitriev",
  "email": "tigerdim@gmail.com",
  "telegram": "dmiit3iy",
  "password": "123"
}

### Создание пользователя
POST http://localhost:8080/users/add
content-type:application/json

{
  "firstName": "Oleg",
  "lastName": "Kolevalov",
  "email": "kol@gmail.com",
  "telegram": "@kol",
  "password": "123"
}

### Создание заметки с ошибкой
POST http://localhost:8080/domain/api/v1/reminder/create
content-type: application/json

{
  "title": "Пробе пера",
  "description": "Много много строчек разных мыслей",
  "remind": "2024-09-27T10-00-00",
  "user": ""
}

### Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "Проба пера",
  "description": "Много много строчек разных мыслей",
  "remind": "2024-09-27T10:00:00"
}

###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "2Проба пера",
  "description": "2Много много строчек разных мыслей",
  "remind": "2024-09-18T11:00:00"
}

###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "3Проба пера",
  "description": "3Много много строчек разных мыслей",
  "remind": "2024-09-17T10:30:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "4Проба пера",
  "description": "4Много много строчек разных мыслей",
  "remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "5Проба пера",
  "description": "5Много много строчек разных мыслей",
  "remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "6Проба пера",
  "description": "6Много много строчек разных мыслей",
  "remind": "2024-09-11T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
"title": "7Проба пера",
"description": "7Много много строчек разных мыслей",
"remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
"title": "8Проба пера",
"description": "8Много много строчек разных мыслей",
"remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "9Проба пера",
  "description": "9Много много строчек разных мыслей",
  "remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "10Проба пера",
  "description": "10Много много строчек разных мыслей",
  "remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "11Проба пера",
  "description": "11Много много строчек разных мыслей",
  "remind": "2024-09-17T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "12Проба пера",
  "description": "12Много много строчек разных мыслей",
  "remind": "2024-09-25T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "13Проба пера",
  "description": "13Много много строчек разных мыслей",
  "remind": "2024-09-28T10:00:00"
}
###Создание заметки
POST http://localhost:8080/domain/api/v1/reminder/create/1
content-type: application/json

{
  "title": "14Проба пера",
  "description": "14Много много строчек разных мыслей",
  "remind": "2024-09-29T11:00:00"
}