### Получение всех напоминаний с пагинацией
GET localhost:8080/domain/api/v1/list/1?current=1&total=3
###Получение всех напоминаний с пагинацией(параметры по умолчанию)
GET localhost:8080/domain/api/v1/list/1
### Получение отсортированного списка по заголовку
GET localhost:8080/domain/api/v1/sort/1?by=title

###Получение отсортированного списка по дате
GET localhost:8080/domain/api/v1/sort/1?by=date

###Получение отсортированного списка по времени напоминания
GET localhost:8080/domain/api/v1/sort/1?by=time

### Фильтр по времени и дате
GET localhost:8080/domain/api/v1/filtr/1?date=2024-09-17&time=10:00:00
### Фильтр по дате
GET localhost:8080/domain/api/v1/filtr/1?date=2024-09-17
### Фильтр по времени
GET localhost:8080/domain/api/v1/filtr/1?time=10:00:00
### Обновление напоминания
PUT localhost:8080/domain/api/v1/reminder/update/1
content-type:application/json

{
  "id": 3,
  "title": "Проба пераQQQQ",
  "description": "Много много строчек разных мыслей",
  "remind": "2024-09-17T10:00:00"
}

###Получение пользвателя
GET localhost:8080/users/1

###Попытка получения пользвателя которого нет в БД
GET localhost:8080/users/1622


### Поиск по времени
GET localhost:8080/domain/api/v1/reminder/search/1?time=10:00:00

### Поиск по дате и времения
GET localhost:8080/domain/api/v1/reminder/search/1?date=2024-09-17&time=10:12:00


