spring:
  application:
    name: Reminder
  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL10Dialect